import { join } from "node:path";

import { extractFrames, type FrameTable } from "./animations";
import { formatWithRepoConfig, gameCache } from "./game-files";
import { extractMonsters, type Monsters } from "./monsters";
import {
  extractPlayerAnimations,
  extractSkillModes,
  type PlayerAnimations,
  type SkillModes,
} from "./skill-animations";
import { extractSkillItemTypes, type SkillItemTypesById } from "./skill-item-types";
import { extractWeapons, type ExtractedWeapon } from "./weapons";

const outputPath = join(import.meta.dir, "..", "src/data/generated/game-data.ts");

interface Extracted {
  readonly version: string;
  readonly weapons: readonly ExtractedWeapon[];
  readonly frames: FrameTable;
  readonly skillModes: SkillModes;
  readonly skillItemTypes: SkillItemTypesById;
  readonly animations: PlayerAnimations;
  readonly monsters: Monsters;
}

function render({
  version,
  weapons,
  frames,
  skillModes,
  skillItemTypes,
  animations,
  monsters,
}: Extracted): string {
  return `/**
 * Generated by \`bun run data:extract\` from Diablo II: Resurrected ${version}. Do not edit.
 *
 * @module
 */
/* oxlint-disable max-lines -- generated data, one object per weapon base and per animation */
import type { WeaponId } from "@/contracts/build";
import type { GameData, WeaponData } from "@/contracts/game-data";

type ExtractedWeapon = Omit<WeaponData, "id"> & { readonly id: string };

function branded(weapon: ExtractedWeapon): WeaponData {
  // SAFETY: extract-data.ts builds every id with slugify and rejects duplicates.
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- a brand has no runtime check: extract-data.ts is the only writer of these ids
  return { ...weapon, id: weapon.id as WeaponId };
}

const weapons: readonly ExtractedWeapon[] = ${JSON.stringify(weapons)};

export const gameData: GameData = {
  version: ${JSON.stringify(version)},
  weapons: weapons.map((weapon) => branded(weapon)),
  frames: ${JSON.stringify(frames)},
  skillModes: ${JSON.stringify(skillModes)},
  skillItemTypes: ${JSON.stringify(skillItemTypes)},
  animations: ${JSON.stringify(animations)},
  monsterAnimations: ${JSON.stringify(monsters.animations)},
  wereforms: ${JSON.stringify(monsters.wereforms)},
  mercenaries: ${JSON.stringify(monsters.mercenaries)},
};
`;
}

const cache = await gameCache();
const weapons = await extractWeapons(cache);
const frames = await extractFrames(cache);
const skillModes = await extractSkillModes(cache);
const skillItemTypes = await extractSkillItemTypes(cache);
const animations = await extractPlayerAnimations(cache, skillModes);
const monsters = await extractMonsters(cache);

const frameEntries = Object.values(frames).reduce(
  (count, characters) => count + Object.keys(characters).length,
  0,
);

const animationEntries = Object.values(animations).reduce(
  (count, names) => count + Object.keys(names).length,
  0,
);

await Bun.write(
  outputPath,
  render({
    version: cache.version,
    weapons,
    frames,
    skillModes,
    skillItemTypes,
    animations,
    monsters,
  }),
);

await formatWithRepoConfig(outputPath);

console.log(
  `${outputPath}: ${cache.version}, ${weapons.length} weapons, ${frameEntries} frame entries, ${Object.keys(skillModes).length} skill modes, ${animationEntries} animations, ${Object.keys(monsters.mercenaries).length} mercenaries`,
);
